---
name: test ci
on:
  push:
    branches:
      - automate

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: install python
        run: sudo apt install python3 
 
      - name: checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: sudo apt-get update
      - name: install venv
        run: sudo apt-get install -y python3-venv
      
      - name: build installing pip and build
        run: sudo apt install pip

      - name: upgrade python build
        run: python -m pip install --upgrade build

      - name: build docker
        run: docker build -t devops-job-tracker:latest .

      
